CREATE DATABASE IF NOT EXISTS eproc;
CREATE DATABASE IF NOT EXISTS eproc_perencanaan;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, CREATE TEMPORARY TABLES
	ON eproc.* TO 'eproc_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, CREATE TEMPORARY TABLES
	ON eproc_perencanaan.* TO 'eproc_app'@'%';
FLUSH PRIVILEGES;
